spring:
  application:
    name: lab-equipment-system
  datasource:
    url: jdbc:mysql://localhost:3307/lab_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3434
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
